# Generated by Django 4.2 on 2023-04-18 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_id_alter_todolist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
