# Generated by Django 4.2 on 2023-04-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_alter_todoitem_id_alter_todolist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassItem',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('weekday', models.CharField(choices=[('شنبه', 'Saturday'), ('یکشنبه', 'Sunday'), ('دوشنبه', 'Monday'), ('سه شنبه', 'Tuesday'), ('چهارشنبه', 'Wednesday'), ('پنچشنبه', 'Thursday'), ('جمعه', 'Friday')], max_length=60)),
                ('location', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
