# Generated by Django 4.2 on 2023-04-23 10:24

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_classitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
